// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cxmate.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	cxmate.proto

It has these top-level messages:
	NetworkElement
	Parameter
	Error
	Node
	Edge
	NodeAttribute
	EdgeAttribute
	NetworkAttribute
	CartesianLayout
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// NetworkElement is a wrapper that constains a label, which is used to allow
// StreamNetworks to send and receive more than one network.NetworkElement is also a wrapper for exactly one element.
// Some elements do not exist in CX, like Parameter and Error, which are special elements used to communicate out of band information
// between cxMate and a service. The other elements corrospond to an aspect in a CX document. These
// elements should be used to build networks, and turn networks back into elements cxMate can understand.
type NetworkElement struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	// Types that are valid to be assigned to Element:
	//	*NetworkElement_Parameter
	//	*NetworkElement_Error
	//	*NetworkElement_Node
	//	*NetworkElement_Edge
	//	*NetworkElement_NodeAttribute
	//	*NetworkElement_EdgeAttribute
	//	*NetworkElement_NetworkAttribute
	//	*NetworkElement_CartesianLayout
	Element isNetworkElement_Element `protobuf_oneof:"element"`
}

func (m *NetworkElement) Reset()                    { *m = NetworkElement{} }
func (m *NetworkElement) String() string            { return proto1.CompactTextString(m) }
func (*NetworkElement) ProtoMessage()               {}
func (*NetworkElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isNetworkElement_Element interface {
	isNetworkElement_Element()
}

type NetworkElement_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,2,opt,name=parameter,oneof"`
}
type NetworkElement_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,oneof"`
}
type NetworkElement_Node struct {
	Node *Node `protobuf:"bytes,4,opt,name=node,oneof"`
}
type NetworkElement_Edge struct {
	Edge *Edge `protobuf:"bytes,5,opt,name=edge,oneof"`
}
type NetworkElement_NodeAttribute struct {
	NodeAttribute *NodeAttribute `protobuf:"bytes,6,opt,name=nodeAttribute,oneof"`
}
type NetworkElement_EdgeAttribute struct {
	EdgeAttribute *EdgeAttribute `protobuf:"bytes,7,opt,name=edgeAttribute,oneof"`
}
type NetworkElement_NetworkAttribute struct {
	NetworkAttribute *NetworkAttribute `protobuf:"bytes,8,opt,name=networkAttribute,oneof"`
}
type NetworkElement_CartesianLayout struct {
	CartesianLayout *CartesianLayout `protobuf:"bytes,9,opt,name=cartesianLayout,oneof"`
}

func (*NetworkElement_Parameter) isNetworkElement_Element()        {}
func (*NetworkElement_Error) isNetworkElement_Element()            {}
func (*NetworkElement_Node) isNetworkElement_Element()             {}
func (*NetworkElement_Edge) isNetworkElement_Element()             {}
func (*NetworkElement_NodeAttribute) isNetworkElement_Element()    {}
func (*NetworkElement_EdgeAttribute) isNetworkElement_Element()    {}
func (*NetworkElement_NetworkAttribute) isNetworkElement_Element() {}
func (*NetworkElement_CartesianLayout) isNetworkElement_Element()  {}

func (m *NetworkElement) GetElement() isNetworkElement_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *NetworkElement) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *NetworkElement) GetParameter() *Parameter {
	if x, ok := m.GetElement().(*NetworkElement_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (m *NetworkElement) GetError() *Error {
	if x, ok := m.GetElement().(*NetworkElement_Error); ok {
		return x.Error
	}
	return nil
}

func (m *NetworkElement) GetNode() *Node {
	if x, ok := m.GetElement().(*NetworkElement_Node); ok {
		return x.Node
	}
	return nil
}

func (m *NetworkElement) GetEdge() *Edge {
	if x, ok := m.GetElement().(*NetworkElement_Edge); ok {
		return x.Edge
	}
	return nil
}

func (m *NetworkElement) GetNodeAttribute() *NodeAttribute {
	if x, ok := m.GetElement().(*NetworkElement_NodeAttribute); ok {
		return x.NodeAttribute
	}
	return nil
}

func (m *NetworkElement) GetEdgeAttribute() *EdgeAttribute {
	if x, ok := m.GetElement().(*NetworkElement_EdgeAttribute); ok {
		return x.EdgeAttribute
	}
	return nil
}

func (m *NetworkElement) GetNetworkAttribute() *NetworkAttribute {
	if x, ok := m.GetElement().(*NetworkElement_NetworkAttribute); ok {
		return x.NetworkAttribute
	}
	return nil
}

func (m *NetworkElement) GetCartesianLayout() *CartesianLayout {
	if x, ok := m.GetElement().(*NetworkElement_CartesianLayout); ok {
		return x.CartesianLayout
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NetworkElement) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _NetworkElement_OneofMarshaler, _NetworkElement_OneofUnmarshaler, _NetworkElement_OneofSizer, []interface{}{
		(*NetworkElement_Parameter)(nil),
		(*NetworkElement_Error)(nil),
		(*NetworkElement_Node)(nil),
		(*NetworkElement_Edge)(nil),
		(*NetworkElement_NodeAttribute)(nil),
		(*NetworkElement_EdgeAttribute)(nil),
		(*NetworkElement_NetworkAttribute)(nil),
		(*NetworkElement_CartesianLayout)(nil),
	}
}

func _NetworkElement_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*NetworkElement)
	// element
	switch x := m.Element.(type) {
	case *NetworkElement_Parameter:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Parameter); err != nil {
			return err
		}
	case *NetworkElement_Error:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *NetworkElement_Node:
		b.EncodeVarint(4<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Node); err != nil {
			return err
		}
	case *NetworkElement_Edge:
		b.EncodeVarint(5<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Edge); err != nil {
			return err
		}
	case *NetworkElement_NodeAttribute:
		b.EncodeVarint(6<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.NodeAttribute); err != nil {
			return err
		}
	case *NetworkElement_EdgeAttribute:
		b.EncodeVarint(7<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.EdgeAttribute); err != nil {
			return err
		}
	case *NetworkElement_NetworkAttribute:
		b.EncodeVarint(8<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.NetworkAttribute); err != nil {
			return err
		}
	case *NetworkElement_CartesianLayout:
		b.EncodeVarint(9<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.CartesianLayout); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NetworkElement.Element has unexpected type %T", x)
	}
	return nil
}

func _NetworkElement_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*NetworkElement)
	switch tag {
	case 2: // element.parameter
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Parameter)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_Parameter{msg}
		return true, err
	case 3: // element.error
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_Error{msg}
		return true, err
	case 4: // element.node
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Node)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_Node{msg}
		return true, err
	case 5: // element.edge
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Edge)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_Edge{msg}
		return true, err
	case 6: // element.nodeAttribute
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(NodeAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_NodeAttribute{msg}
		return true, err
	case 7: // element.edgeAttribute
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(EdgeAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_EdgeAttribute{msg}
		return true, err
	case 8: // element.networkAttribute
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(NetworkAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_NetworkAttribute{msg}
		return true, err
	case 9: // element.cartesianLayout
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(CartesianLayout)
		err := b.DecodeMessage(msg)
		m.Element = &NetworkElement_CartesianLayout{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NetworkElement_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*NetworkElement)
	// element
	switch x := m.Element.(type) {
	case *NetworkElement_Parameter:
		s := proto1.Size(x.Parameter)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_Error:
		s := proto1.Size(x.Error)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_Node:
		s := proto1.Size(x.Node)
		n += proto1.SizeVarint(4<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_Edge:
		s := proto1.Size(x.Edge)
		n += proto1.SizeVarint(5<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_NodeAttribute:
		s := proto1.Size(x.NodeAttribute)
		n += proto1.SizeVarint(6<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_EdgeAttribute:
		s := proto1.Size(x.EdgeAttribute)
		n += proto1.SizeVarint(7<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_NetworkAttribute:
		s := proto1.Size(x.NetworkAttribute)
		n += proto1.SizeVarint(8<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NetworkElement_CartesianLayout:
		s := proto1.Size(x.CartesianLayout)
		n += proto1.SizeVarint(9<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Parameter represents a named value passed from cxMate to the service.
// A service should never send a Parameter to cxMate, it will be discarded.
// Parameters are usually used to pass query string parameters (?key=value pairs in a URL)
// to a service for small tweaks to the way a service runs.
type Parameter struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Parameter_StringValue
	//	*Parameter_BooleanValue
	//	*Parameter_IntegerValue
	//	*Parameter_NumberValue
	Value isParameter_Value `protobuf_oneof:"value"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto1.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isParameter_Value interface {
	isParameter_Value()
}

type Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=stringValue,oneof"`
}
type Parameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=booleanValue,oneof"`
}
type Parameter_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,5,opt,name=integerValue,oneof"`
}
type Parameter_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,6,opt,name=numberValue,oneof"`
}

func (*Parameter_StringValue) isParameter_Value()  {}
func (*Parameter_BooleanValue) isParameter_Value() {}
func (*Parameter_IntegerValue) isParameter_Value() {}
func (*Parameter_NumberValue) isParameter_Value()  {}

func (m *Parameter) GetValue() isParameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Parameter) GetStringValue() string {
	if x, ok := m.GetValue().(*Parameter_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Parameter) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Parameter_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Parameter) GetIntegerValue() int64 {
	if x, ok := m.GetValue().(*Parameter_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (m *Parameter) GetNumberValue() float64 {
	if x, ok := m.GetValue().(*Parameter_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Parameter) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _Parameter_OneofMarshaler, _Parameter_OneofUnmarshaler, _Parameter_OneofSizer, []interface{}{
		(*Parameter_StringValue)(nil),
		(*Parameter_BooleanValue)(nil),
		(*Parameter_IntegerValue)(nil),
		(*Parameter_NumberValue)(nil),
	}
}

func _Parameter_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*Parameter)
	// value
	switch x := m.Value.(type) {
	case *Parameter_StringValue:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Parameter_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto1.WireVarint)
		b.EncodeVarint(t)
	case *Parameter_IntegerValue:
		b.EncodeVarint(5<<3 | proto1.WireVarint)
		b.EncodeVarint(uint64(x.IntegerValue))
	case *Parameter_NumberValue:
		b.EncodeVarint(6<<3 | proto1.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.NumberValue))
	case nil:
	default:
		return fmt.Errorf("Parameter.Value has unexpected type %T", x)
	}
	return nil
}

func _Parameter_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*Parameter)
	switch tag {
	case 3: // value.stringValue
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Parameter_StringValue{x}
		return true, err
	case 4: // value.booleanValue
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Parameter_BooleanValue{x != 0}
		return true, err
	case 5: // value.integerValue
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Parameter_IntegerValue{int64(x)}
		return true, err
	case 6: // value.numberValue
		if wire != proto1.WireFixed64 {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Parameter_NumberValue{math.Float64frombits(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Parameter_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*Parameter)
	// value
	switch x := m.Value.(type) {
	case *Parameter_StringValue:
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Parameter_BooleanValue:
		n += proto1.SizeVarint(4<<3 | proto1.WireVarint)
		n += 1
	case *Parameter_IntegerValue:
		n += proto1.SizeVarint(5<<3 | proto1.WireVarint)
		n += proto1.SizeVarint(uint64(x.IntegerValue))
	case *Parameter_NumberValue:
		n += proto1.SizeVarint(6<<3 | proto1.WireFixed64)
		n += 8
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Error represents an error from either cxMate or the service. Errors sent
// from the service to cxMate will be encoded in the final JSON response returned to
// the REST client. Sending back good error messages is good practice.
type Error struct {
	Status  int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Code    string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Link    string `protobuf:"bytes,4,opt,name=link" json:"link,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

// Node represents a single node in a network.
type Node struct {
	Id         int64  `protobuf:"varint,1,opt,name=id,json=@id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	Represents string `protobuf:"bytes,3,opt,name=represents,json=r" json:"represents,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto1.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetRepresents() string {
	if m != nil {
		return m.Represents
	}
	return ""
}

// Edge represents a single edge in a network.
type Edge struct {
	Id          int64  `protobuf:"varint,1,opt,name=id,json=@id" json:"id,omitempty"`
	SourceId    int64  `protobuf:"varint,2,opt,name=sourceId,json=s" json:"sourceId,omitempty"`
	TargetId    int64  `protobuf:"varint,3,opt,name=targetId,json=t" json:"targetId,omitempty"`
	Interaction string `protobuf:"bytes,4,opt,name=interaction,json=i" json:"interaction,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto1.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Edge) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Edge) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Edge) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Edge) GetInteraction() string {
	if m != nil {
		return m.Interaction
	}
	return ""
}

// NodeAttribute represents a single attribute attached to a node.
type NodeAttribute struct {
	NodeId int64  `protobuf:"varint,1,opt,name=nodeId,json=po" json:"nodeId,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	//  google.protobuf.Any value = 3 [ json_name = "v" ];
	Value string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type  string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
}

func (m *NodeAttribute) Reset()                    { *m = NodeAttribute{} }
func (m *NodeAttribute) String() string            { return proto1.CompactTextString(m) }
func (*NodeAttribute) ProtoMessage()               {}
func (*NodeAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NodeAttribute) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *NodeAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NodeAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// EdgeAttribute represents a single attribute attached to an edge.
type EdgeAttribute struct {
	EdgeId int64  `protobuf:"varint,1,opt,name=edgeId,json=po" json:"edgeId,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	//  google.protobuf.Any value = 3 [ json_name = "v" ];
	Value string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type  string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
}

func (m *EdgeAttribute) Reset()                    { *m = EdgeAttribute{} }
func (m *EdgeAttribute) String() string            { return proto1.CompactTextString(m) }
func (*EdgeAttribute) ProtoMessage()               {}
func (*EdgeAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EdgeAttribute) GetEdgeId() int64 {
	if m != nil {
		return m.EdgeId
	}
	return 0
}

func (m *EdgeAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EdgeAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EdgeAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// NetworkAttribute represents a single attribute attached to a network.
type NetworkAttribute struct {
	Name string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	//  google.protobuf.Any value = 3 [ json_name = "v" ];
	Value string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type  string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
}

func (m *NetworkAttribute) Reset()                    { *m = NetworkAttribute{} }
func (m *NetworkAttribute) String() string            { return proto1.CompactTextString(m) }
func (*NetworkAttribute) ProtoMessage()               {}
func (*NetworkAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NetworkAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NetworkAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// CartesianLayout represents an (x,y,(z)) coordinate attached to a node.
type CartesianLayout struct {
	NodeId int64   `protobuf:"varint,1,opt,name=nodeId,json=node" json:"nodeId,omitempty"`
	X      float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y      float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Z      float64 `protobuf:"fixed64,4,opt,name=z" json:"z,omitempty"`
}

func (m *CartesianLayout) Reset()                    { *m = CartesianLayout{} }
func (m *CartesianLayout) String() string            { return proto1.CompactTextString(m) }
func (*CartesianLayout) ProtoMessage()               {}
func (*CartesianLayout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CartesianLayout) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *CartesianLayout) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CartesianLayout) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CartesianLayout) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto1.RegisterType((*NetworkElement)(nil), "proto.NetworkElement")
	proto1.RegisterType((*Parameter)(nil), "proto.Parameter")
	proto1.RegisterType((*Error)(nil), "proto.Error")
	proto1.RegisterType((*Node)(nil), "proto.Node")
	proto1.RegisterType((*Edge)(nil), "proto.Edge")
	proto1.RegisterType((*NodeAttribute)(nil), "proto.NodeAttribute")
	proto1.RegisterType((*EdgeAttribute)(nil), "proto.EdgeAttribute")
	proto1.RegisterType((*NetworkAttribute)(nil), "proto.NetworkAttribute")
	proto1.RegisterType((*CartesianLayout)(nil), "proto.CartesianLayout")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CxMateService service

type CxMateServiceClient interface {
	// StreamElements allows cxMate to stream one or more networks to a service
	// which can then stream one or more networks back.
	StreamNetworks(ctx context.Context, opts ...grpc.CallOption) (CxMateService_StreamNetworksClient, error)
}

type cxMateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCxMateServiceClient(cc *grpc.ClientConn) CxMateServiceClient {
	return &cxMateServiceClient{cc}
}

func (c *cxMateServiceClient) StreamNetworks(ctx context.Context, opts ...grpc.CallOption) (CxMateService_StreamNetworksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CxMateService_serviceDesc.Streams[0], c.cc, "/proto.cxMateService/StreamNetworks", opts...)
	if err != nil {
		return nil, err
	}
	x := &cxMateServiceStreamNetworksClient{stream}
	return x, nil
}

type CxMateService_StreamNetworksClient interface {
	Send(*NetworkElement) error
	Recv() (*NetworkElement, error)
	grpc.ClientStream
}

type cxMateServiceStreamNetworksClient struct {
	grpc.ClientStream
}

func (x *cxMateServiceStreamNetworksClient) Send(m *NetworkElement) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cxMateServiceStreamNetworksClient) Recv() (*NetworkElement, error) {
	m := new(NetworkElement)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CxMateService service

type CxMateServiceServer interface {
	// StreamElements allows cxMate to stream one or more networks to a service
	// which can then stream one or more networks back.
	StreamNetworks(CxMateService_StreamNetworksServer) error
}

func RegisterCxMateServiceServer(s *grpc.Server, srv CxMateServiceServer) {
	s.RegisterService(&_CxMateService_serviceDesc, srv)
}

func _CxMateService_StreamNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CxMateServiceServer).StreamNetworks(&cxMateServiceStreamNetworksServer{stream})
}

type CxMateService_StreamNetworksServer interface {
	Send(*NetworkElement) error
	Recv() (*NetworkElement, error)
	grpc.ServerStream
}

type cxMateServiceStreamNetworksServer struct {
	grpc.ServerStream
}

func (x *cxMateServiceStreamNetworksServer) Send(m *NetworkElement) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cxMateServiceStreamNetworksServer) Recv() (*NetworkElement, error) {
	m := new(NetworkElement)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CxMateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.cxMateService",
	HandlerType: (*CxMateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNetworks",
			Handler:       _CxMateService_StreamNetworks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cxmate.proto",
}

func init() { proto1.RegisterFile("cxmate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x6f, 0xd3, 0x4a,
	0x10, 0xc7, 0xbd, 0x75, 0x7e, 0xd4, 0x93, 0xb4, 0x89, 0xf6, 0xb5, 0x7d, 0xd6, 0x3b, 0xf5, 0x59,
	0x3d, 0xf4, 0x54, 0x55, 0xe5, 0x8a, 0x04, 0x14, 0x82, 0x5c, 0x09, 0x2a, 0xd8, 0x0a, 0x10, 0xc7,
	0x8d, 0x3d, 0x44, 0x56, 0xe3, 0xdd, 0x68, 0xbd, 0x29, 0x49, 0xff, 0x4e, 0xc4, 0xdf, 0x83, 0x66,
	0xbd, 0x6e, 0xe3, 0x94, 0x13, 0x9c, 0xb2, 0x33, 0xf3, 0x9d, 0xcf, 0xce, 0xec, 0x4c, 0x0c, 0xc3,
	0x6c, 0x55, 0x4a, 0x8b, 0x67, 0x0b, 0xa3, 0xad, 0xe6, 0x5d, 0xf7, 0x93, 0xfc, 0x0c, 0x61, 0xff,
	0x1a, 0xed, 0x77, 0x6d, 0x6e, 0x27, 0x73, 0x2c, 0x51, 0x59, 0x7e, 0x00, 0xdd, 0xb9, 0x9c, 0xe2,
	0x3c, 0x66, 0xc7, 0xec, 0x34, 0x12, 0xb5, 0xc1, 0xcf, 0x21, 0x5a, 0x48, 0x23, 0x4b, 0xb4, 0x68,
	0xe2, 0x9d, 0x63, 0x76, 0x3a, 0xb8, 0x18, 0xd7, 0xa8, 0xb3, 0x0f, 0x8d, 0x3f, 0x0d, 0xc4, 0xa3,
	0x88, 0x9f, 0x40, 0x17, 0x8d, 0xd1, 0x26, 0x0e, 0x9d, 0x7a, 0xe8, 0xd5, 0x13, 0xf2, 0xa5, 0x81,
	0xa8, 0x83, 0xfc, 0x7f, 0xe8, 0x28, 0x9d, 0x63, 0xdc, 0x71, 0xa2, 0x81, 0x17, 0x5d, 0xeb, 0x1c,
	0xd3, 0x40, 0xb8, 0x10, 0x49, 0x30, 0x9f, 0x61, 0xdc, 0x6d, 0x49, 0x26, 0xf9, 0xcc, 0x49, 0x28,
	0xc4, 0x9f, 0xc3, 0x1e, 0x49, 0x5f, 0x59, 0x6b, 0x8a, 0xe9, 0xd2, 0x62, 0xdc, 0x73, 0xda, 0x83,
	0x0d, 0xdc, 0x43, 0x2c, 0x0d, 0x44, 0x5b, 0x4c, 0xd9, 0x44, 0x79, 0xcc, 0xee, 0xb7, 0xb2, 0x27,
	0x9b, 0x31, 0xca, 0x6e, 0x89, 0xf9, 0x04, 0xc6, 0xaa, 0x7e, 0xc1, 0x47, 0xc0, 0xae, 0x03, 0xfc,
	0xdb, 0x5c, 0xbf, 0x15, 0x4e, 0x03, 0xf1, 0x24, 0x85, 0x5f, 0xc2, 0x28, 0x93, 0xc6, 0x62, 0x55,
	0x48, 0xf5, 0x4e, 0xae, 0xf5, 0xd2, 0xc6, 0x91, 0xa3, 0x1c, 0x79, 0xca, 0xeb, 0x76, 0x34, 0x0d,
	0xc4, 0x76, 0xc2, 0x65, 0x04, 0x7d, 0xac, 0xa7, 0x98, 0xfc, 0x60, 0x10, 0x3d, 0x0c, 0x86, 0x73,
	0xe8, 0x28, 0x59, 0xa2, 0x1f, 0xa9, 0x3b, 0xf3, 0x23, 0xe8, 0x7d, 0xd3, 0xa6, 0x94, 0xd6, 0x8d,
	0x33, 0x12, 0xde, 0xe2, 0x09, 0x0c, 0x2a, 0x6b, 0x0a, 0x35, 0xfb, 0x2c, 0xe7, 0x4b, 0x74, 0xd3,
	0x8b, 0xd2, 0x40, 0x6c, 0x3a, 0xf9, 0x09, 0x0c, 0xa7, 0x5a, 0xcf, 0x51, 0xaa, 0x5a, 0x44, 0xd3,
	0xdb, 0x4d, 0x03, 0xd1, 0xf2, 0x92, 0xaa, 0x50, 0x16, 0x67, 0x68, 0x6a, 0x15, 0x0d, 0x30, 0x24,
	0xd5, 0xa6, 0x97, 0xee, 0x53, 0xcb, 0x72, 0xda, 0x88, 0x68, 0x72, 0x8c, 0xee, 0xdb, 0x70, 0x5e,
	0xf6, 0xa1, 0x7b, 0x47, 0x87, 0x44, 0x42, 0xd7, 0x2d, 0x10, 0x55, 0x5f, 0x59, 0x69, 0x97, 0x95,
	0xeb, 0x29, 0x14, 0xde, 0xa2, 0x4e, 0x33, 0xda, 0xa7, 0xba, 0x27, 0x77, 0xe6, 0x31, 0xf4, 0x4b,
	0xac, 0x2a, 0x39, 0xf3, 0xdd, 0x88, 0xc6, 0x24, 0xf5, 0xbc, 0x50, 0xb7, 0xae, 0xfe, 0x48, 0xb8,
	0x73, 0xf2, 0x02, 0x3a, 0xb4, 0x2f, 0x7c, 0x04, 0x3b, 0x45, 0xee, 0xe9, 0xe1, 0xcb, 0x22, 0xe7,
	0x23, 0xff, 0x88, 0x35, 0x9a, 0x29, 0x7e, 0x08, 0x60, 0x70, 0x61, 0xb0, 0x42, 0x65, 0x2b, 0x8f,
	0x66, 0x26, 0xf9, 0x0a, 0x1d, 0x5a, 0x99, 0xa7, 0x80, 0x7f, 0x60, 0xb7, 0xd2, 0x4b, 0x93, 0xe1,
	0x55, 0xee, 0x20, 0xa1, 0x60, 0x15, 0x39, 0xad, 0x34, 0x33, 0xb4, 0x57, 0xb9, 0x43, 0x84, 0x82,
	0x59, 0x7e, 0x04, 0x03, 0x7a, 0x23, 0x23, 0x33, 0x5b, 0x68, 0xe5, 0xcb, 0x63, 0x45, 0xf2, 0x05,
	0xf6, 0x5a, 0xbb, 0xcc, 0x39, 0xf4, 0x68, 0x97, 0xaf, 0x9a, 0x7b, 0x76, 0x16, 0xfa, 0x69, 0x9d,
	0x63, 0xff, 0x7a, 0x4d, 0x89, 0x77, 0x24, 0xb1, 0xeb, 0x05, 0x36, 0xe0, 0x9c, 0xc0, 0xad, 0x35,
	0x27, 0x30, 0xad, 0xf9, 0x5f, 0x83, 0xdf, 0xc2, 0x78, 0x7b, 0xfd, 0xff, 0x88, 0xf3, 0x11, 0x46,
	0x5b, 0x7f, 0x00, 0x7e, 0xb0, 0xd5, 0x7b, 0xfd, 0xb5, 0x18, 0x02, 0x5b, 0x39, 0x32, 0x13, 0x6c,
	0x45, 0xd6, 0xda, 0x51, 0x99, 0x60, 0x6b, 0xb2, 0xee, 0x1d, 0x92, 0x09, 0x76, 0x7f, 0xf1, 0x09,
	0xf6, 0xb2, 0xd5, 0x7b, 0x69, 0xf1, 0x06, 0xcd, 0x5d, 0x91, 0x21, 0x7f, 0x03, 0xfb, 0x37, 0xd6,
	0xa0, 0x2c, 0x7d, 0xc5, 0x15, 0x3f, 0x6c, 0xff, 0x83, 0xfd, 0x27, 0xf2, 0xbf, 0xdf, 0xbb, 0x93,
	0xe0, 0x94, 0x9d, 0xb3, 0x69, 0xcf, 0xc5, 0x9e, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xd7,
	0xf8, 0x65, 0x70, 0x05, 0x00, 0x00,
}
